-- Gradiente · más cosas que edita el equipo (organizadores y admins) desde la página.
-- Los datos de data/*.json quedan de respaldo si Supabase no responde.

-- 1) avisos marcados en el calendario (paros, días sin clases, eventos)
alter table public.avisos add column in_cal boolean not null default true;
grant select (in_cal) on public.avisos to anon, authenticated;

-- 2) links útiles (Recursos)
create table public.links (
  id          uuid primary key default gen_random_uuid(),
  title       text not null check (char_length(title) between 2 and 120),
  label       text check (char_length(label) <= 120),
  url         text not null check (url ~* '^(https?://|mailto:|/|#)' and char_length(url) <= 500),
  category    text not null default 'Otros' check (char_length(category) <= 40),
  description text check (char_length(description) <= 300),
  tags        text[] not null default '{}',
  audience    text[] not null default '{}',
  priority    integer not null default 50,
  active      boolean not null default true,
  updated_at  timestamptz not null default now()
);
alter table public.links enable row level security;
create policy "links: ver"            on public.links for select to anon, authenticated using (active or (select public.is_staff()));
create policy "links: el equipo crea" on public.links for insert to authenticated with check ((select public.is_staff()));
create policy "links: el equipo edita" on public.links for update to authenticated using ((select public.is_staff())) with check ((select public.is_staff()));
create policy "links: el equipo borra" on public.links for delete to authenticated using ((select public.is_staff()));
create trigger links_touch before update on public.links for each row execute function public.kiosco_touch();

-- 3) preguntas frecuentes (chat de Ayuda)
create table public.faq (
  id          text primary key check (id ~ '^[a-z0-9-]{2,40}$'),
  topic       text not null check (char_length(topic) <= 40),
  q           text not null check (char_length(q) between 4 and 200),
  a           text[] not null check (cardinality(a) between 1 and 8),
  k           text[] not null default '{}',
  links       jsonb not null default '[]'::jsonb,
  top         integer,
  priority    integer not null default 50,
  active      boolean not null default true,
  updated_at  timestamptz not null default now()
);
alter table public.faq enable row level security;
create policy "faq: ver"            on public.faq for select to anon, authenticated using (active or (select public.is_staff()));
create policy "faq: el equipo crea" on public.faq for insert to authenticated with check ((select public.is_staff()));
create policy "faq: el equipo edita" on public.faq for update to authenticated using ((select public.is_staff())) with check ((select public.is_staff()));
create policy "faq: el equipo borra" on public.faq for delete to authenticated using ((select public.is_staff()));
create trigger faq_touch before update on public.faq for each row execute function public.kiosco_touch();

-- 4) cátedras: correcciones de página y mail por código de materia (lo demás sale de data/catedras.json)
create table public.catedras (
  code        text primary key check (code ~ '^[A-Za-z0-9]{2,12}$'),
  page        text check (char_length(page) <= 200),
  mail        text check (mail is null or mail ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  updated_at  timestamptz not null default now()
);
alter table public.catedras enable row level security;
create policy "catedras: ver"            on public.catedras for select to anon, authenticated using (true);
create policy "catedras: el equipo crea" on public.catedras for insert to authenticated with check ((select public.is_staff()));
create policy "catedras: el equipo edita" on public.catedras for update to authenticated using ((select public.is_staff())) with check ((select public.is_staff()));
create policy "catedras: el equipo borra" on public.catedras for delete to authenticated using ((select public.is_staff()));
create trigger catedras_touch before update on public.catedras for each row execute function public.kiosco_touch();

grant select on public.links, public.faq, public.catedras to anon, authenticated;

insert into public.links (title, label, url, category, description, tags, audience, priority, active) values
  ('Guia oficial para ingresantes FI-UNLP', 'Guía oficial para ingresantes', 'https://ing.unlp.edu.ar/ingresantes/', 'Ingresantes', 'Todo lo que tenés que saber antes de arrancar.', array['ingreso','primer-ano','oficial']::text[], array['ingresantes']::text[], 1, true),
  ('Catedra de ingreso', 'Cátedra de ingreso', 'https://ing.unlp.edu.ar/grado/catedra-de-ingreso/', 'Ingresantes', 'Matemática para Ingeniería: cronograma y material.', array['matepi','ingreso','oficial']::text[], array['ingresantes']::text[], 2, true),
  ('Calendario ano lectivo completo', 'Calendario académico', 'https://ing.unlp.edu.ar/institucional/calendario-ano-lectivo-completo/', 'Ingresantes', 'Inscripciones, mesas de final y feriados del año.', array['fechas','calendario','oficial']::text[], array['ingresantes','todos']::text[], 3, true),
  ('Programa para estudiantes trabajadores (RET)', 'Estudiantes trabajadores (RET)', 'https://ing.unlp.edu.ar/grado/programa-para-estudiantes-trabajadores/', 'Ingresantes', 'Régimen especial si trabajás mientras estudiás.', array['ret','trabajadores','tramite']::text[], array['ingresantes','todos']::text[], 4, true),
  ('Turnos FI para tramites', 'Turnos para trámites', 'https://ing.unlp.edu.ar/turnos/', 'Ingresantes', 'Pedí turno en alumnos, readmisión y más.', array['turnos','readmision','tramite']::text[], array['ingresantes','todos']::text[], 5, true),
  ('Como generar tu cuenta SIU-Guarani', 'Cuenta SIU Guaraní', 'https://autogestion.guarani.unlp.edu.ar/acceso', 'Ingresantes', 'Inscribite a materias y finales.', array['siu','guarani','autogestion','ingreso']::text[], array['todos']::text[], 6, true),
  ('Aulas y horarios', 'Aulas y horarios', 'https://ing.unlp.edu.ar/grado/aulas/', 'Consultas frecuentes', 'Dónde y cuándo se cursa cada materia.', array['aulas','horarios','cursada']::text[], array['todos']::text[], 2, true),
  ('Portal de Asignaturas FI', 'Portal de Asignaturas', 'https://www.asignaturas.ing.unlp.edu.ar/', 'Consultas frecuentes', 'Las aulas virtuales (Moodle) de cada cátedra.', array['asignaturas','materias','cursada']::text[], array['todos']::text[], 1, true),
  ('Solicitud de correo institucional para alumnos', 'Correo institucional', 'https://www1.ing.unlp.edu.ar/sitio/administracion/soporte/correo_est/', 'Consultas frecuentes', 'Pedí tu cuenta @alu.ing.unlp.edu.ar.', array['correo','cuenta','it']::text[], array['todos']::text[], 3, true),
  ('Prorroga para rendir final', 'Prórroga para rendir final', 'https://docs.google.com/forms/d/e/1FAIpQLSePPkDXvKFLO8kEg4GLGe1_C4qhybkuVpoqPEeU3BDmXdlMbg/viewform', 'Consultas frecuentes', 'Si se te vence la regularidad de una materia.', array['final','prorroga','tramite']::text[], array['todos']::text[], 4, true),
  ('Nube de apuntes y parciales', 'Nube de apuntes y parciales', 'https://drive.google.com/open?id=1nqMOCWnGQf4hijaALpiovu1L5c6PvUJb', 'Parciales y apuntes', 'Parciales, finales y resúmenes por materia.', array['apuntes','parciales','finales']::text[], array['todos']::text[], 1, true),
  ('Formulario para compartir material', null, '#', 'Parciales y apuntes', null, array['colaborar','apuntes']::text[], array['todos']::text[], 2, false),
  ('Becas y pasantias FI', 'Becas y pasantías FI', 'https://ing.unlp.edu.ar/grado/becas-pasantias/', 'Becas y bienestar', 'Todas las becas de la Facultad en un lugar.', array['becas','pasantias','fi']::text[], array['todos']::text[], 1, true),
  ('Pasantias educativas FI', 'Pasantías educativas', 'https://ing.unlp.edu.ar/grado/becas-pasantias/pasantias/', 'Becas y bienestar', 'Prácticas rentadas en empresas e instituciones.', array['pasantia','laboral','oficial']::text[], array['estudiantes','avanzados','todos']::text[], 2, true),
  ('PAE FI (inscripcion y seguimiento de becas)', 'PAE FI', 'https://pae.ing.unlp.edu.ar/inicio/ingresar.php', 'Becas y bienestar', 'Inscripción y seguimiento de becas de la Facultad.', array['pae','becas','fi']::text[], array['todos']::text[], 3, true),
  ('Becas UNLP', 'Becas UNLP', 'https://unlp.edu.ar/gestion/bienestar_universitario/estudiantes/becas-unlp-49157', 'Becas y bienestar', 'Ayuda económica, comedor, transporte y más.', array['unlp','ayuda-economica','comedor']::text[], array['todos']::text[], 4, true),
  ('Albergue universitario UNLP', 'Albergue universitario', 'https://unlp.edu.ar/gestion/estudiantes/bienestar-accesible/albergue/', 'Becas y bienestar', 'Alojamiento para estudiantes de la UNLP.', array['albergue','unlp','bienestar']::text[], array['ingresantes','todos']::text[], 5, true),
  ('Fondo de Becas FI (Devolviendo Oportunidades)', 'Fondo de Becas FI', 'https://ing.unlp.edu.ar/fondo-de-becas/', 'Becas y bienestar', 'Devolviendo Oportunidades: becas de graduados.', array['fondo','becas','fi']::text[], array['todos']::text[], 6, true),
  ('Becas Progresar (oficial)', 'Becas Progresar', 'https://www.argentina.gob.ar/educacion/progresar', 'Becas y bienestar', 'Beca nacional para estudiantes.', array['progresar','nacion','beca']::text[], array['todos']::text[], 7, true),
  ('Becas Manuel Belgrano (oficial)', 'Becas Manuel Belgrano', 'https://www.argentina.gob.ar/educacion/becas/becas-manuel-belgrano', 'Becas y bienestar', 'Beca nacional para carreras estratégicas.', array['belgrano','nacion','beca']::text[], array['todos']::text[], 8, true),
  ('Becas Fundacion YPF', 'Becas Fundación YPF', 'https://becas.fundacionypf.org/', 'Becas y bienestar', 'Becas para carreras de ingeniería y energía.', array['ypf','beca','ingenieria']::text[], array['todos']::text[], 9, true),
  ('Proyectos de extension FI', 'Proyectos de extensión', 'https://ing.unlp.edu.ar/extension/proyectos-de-extension/', 'Proyectos e investigacion', 'Proyectos con la comunidad a los que podés sumarte.', array['extension','proyectos','participar']::text[], array['todos']::text[], 1, true),
  ('Convocatorias de extension FI', 'Convocatorias de extensión', 'https://ing.unlp.edu.ar/extension/', 'Proyectos e investigacion', 'Llamados abiertos y actividades (sirven como AFC).', array['convocatorias','extension','afc']::text[], array['todos']::text[], 2, true),
  ('Proyectos de investigacion y transferencia', 'Investigación y transferencia', 'https://ing.unlp.edu.ar/investigacion/proyectos-de-investigacion-y-transferencia/', 'Proyectos e investigacion', 'Los proyectos que se desarrollan en la FI.', array['investigacion','transferencia','proyectos']::text[], array['estudiantes','avanzados','todos']::text[], 3, true),
  ('UIDETs, laboratorios y centros FI', 'UIDETs, laboratorios y centros', 'https://ing.unlp.edu.ar/investigacion/uidets/', 'Proyectos e investigacion', 'Grupos de investigación donde podés hacer una beca.', array['uidet','laboratorios','investigacion']::text[], array['estudiantes','avanzados','todos']::text[], 4, true),
  ('Novedades de investigacion y transferencia', 'Novedades de investigación', 'https://ing.unlp.edu.ar/novedades/investigacion-y-transferencia/', 'Proyectos e investigacion', 'Lo último de los grupos de la Facultad.', array['novedades','beca-investigacion','convocatoria']::text[], array['todos']::text[], 5, true),
  ('Mapa Facultad 3D (proximamente)', null, '/mapa', 'Mapa Facultad', null, array['mapa','aulas','campus']::text[], array['ingresantes','todos']::text[], 1, true),
  ('Plano oficial del campus FI', 'Plano del campus', 'https://ing.unlp.edu.ar/institucional/plano/', 'Mapa Facultad', 'Edificios, aulas y departamentos.', array['plano','campus','edificios']::text[], array['ingresantes','todos']::text[], 2, true),
  ('Estudiantes FI (tramites, certificados y servicios)', 'Estudiantes FI', 'https://ing.unlp.edu.ar/estudiantes/', 'Institucional', 'Certificados, trámites y servicios para alumnos.', array['estudiantes','tramites','oficial']::text[], array['todos']::text[], 1, true),
  ('Servicios IT FI', 'Servicios IT', 'https://ing.unlp.edu.ar/institucional/servicios_it/', 'Institucional', 'Wifi, cuentas y sistemas de la Facultad.', array['it','moodle','correo']::text[], array['todos']::text[], 3, true),
  ('Consultas a la mesa (formulario)', 'Consultá a Gradiente', 'https://docs.google.com/forms/d/e/1FAIpQLSeGuH8e9_Yb_C6glZLeWzefB3vMLW1RlIgOFwUTw5RWtrd7hA/viewform?usp=publish-editor', 'Contacto', 'Escribinos y te respondemos.', array['consulta','mesa','formulario']::text[], array['ingresantes','todos']::text[], 1, true),
  ('Marcha 12 de mayo: formulario de convocatoria', null, 'https://forms.gle/QZzjTXXHq3uLBATG8', 'Avisos', null, array['marcha','12-de-mayo','convocatoria','formulario']::text[], array['todos']::text[], 50, false),
  ('Feriazo Estudiantil', null, 'https://docs.google.com/forms/d/e/1FAIpQLScVYVR5RSnmdzjr8wR9lZdhanZdTPDEj4tjDMdnpQfLz8zZpQ/viewform?usp=publish-editor', 'Avisos', null, array['feriazo','festival','formulario','emprendimientos']::text[], array['todos']::text[], 1, false),
  ('Direccion de Ensenanza: ensenanza@ing.unlp.edu.ar', 'Dirección de Enseñanza', 'mailto:ensenanza@ing.unlp.edu.ar', 'Contacto', 'Inscripciones, finales y equivalencias.', array['mail','copiar','ensenanza']::text[], array['todos']::text[], 98, true),
  ('Asuntos Estudiantiles: asuntos.estudiantiles@ing.unlp.edu.ar', 'Asuntos Estudiantiles', 'mailto:asuntos.estudiantiles@ing.unlp.edu.ar', 'Contacto', 'Becas, bienestar y situaciones personales.', array['mail','copiar','asuntos-estudiantiles']::text[], array['todos']::text[], 99, true);

insert into public.faq (id, topic, q, a, k, links, top, priority) values
  ('inscripcion', 'cursada', '¿Cómo me inscribo a una materia?', array['Por SIU Guaraní, dentro del período de inscripción que publica la Facultad en el calendario académico.','Si la materia no te aparece, casi siempre es porque te falta alguna correlativa. En Mi plan podés ver qué te falta.']::text[], array['inscribir','inscripcion','anotar','anoto','anotarme','cursar','materia','cursada','siu']::text[], '[{"label":"SIU Guaraní","url":"https://autogestion.guarani.unlp.edu.ar/acceso"},{"label":"Calendario académico","match":"Calendario ano lectivo completo"}]'::jsonb, 1, 1),
  ('que-curso', 'cursada', '¿Qué materias puedo cursar?', array['Depende de las correlativas: para cursar necesitás tenerlas regulares o aprobadas.','Marcá lo que ya hiciste en Mi plan y te mostramos al toque qué podés cursar y qué finales podés rendir.']::text[], array['puedo','cursar','correlativas','correlativa','habilita','siguiente','cuatrimestre','plan']::text[], '[{"label":"Ver qué puedo cursar","go":"#/plan?filtro=ready"}]'::jsonb, 3, 2),
  ('aulas', 'cursada', '¿Dónde veo aulas y horarios?', array['La Facultad publica las aulas y horarios de cada cuatrimestre en su web. Las cátedras suelen avisar cambios en el portal de asignaturas.']::text[], array['aula','aulas','horario','horarios','donde','curso','comision','comisiones','edificio']::text[], '[{"label":"Aulas y horarios","match":"Aulas y horarios"},{"label":"Portal de asignaturas","match":"Portal de Asignaturas FI"}]'::jsonb, 2, 3),
  ('regular', 'cursada', '¿Qué diferencia hay entre regular y aprobada?', array['Regular: aprobaste la cursada y te queda rendir el final.','Aprobada: rendiste el final o la promocionaste. Para rendir un final necesitás las correlativas aprobadas, no solo regulares.']::text[], array['regular','regularizar','aprobada','aprobar','diferencia','promocion','promocionar','final']::text[], '[]'::jsonb, null, 4),
  ('material', 'cursada', '¿Dónde encuentro el material de una materia?', array['Cada cátedra tiene su página en el portal de asignaturas de la Facultad.','Además, en la Nube de Gradiente hay más de 2.600 archivos entre parciales, finales y apuntes, ordenados por materia.']::text[], array['material','apunte','apuntes','teoria','practica','catedra','pagina','moodle','asignatura']::text[], '[{"label":"Portal de asignaturas","match":"Portal de Asignaturas FI"},{"label":"Nube de apuntes","match":"Nube de apuntes y parciales"}]'::jsonb, null, 5),
  ('final-inscripcion', 'finales', '¿Cómo me anoto a un final?', array['También por SIU Guaraní, en las fechas de mesa que figuran en el calendario académico. Anotate con tiempo: la inscripción cierra unos días antes de cada mesa.','Acordate que para rendir necesitás las correlativas aprobadas.']::text[], array['final','finales','mesa','mesas','rendir','examen','anotar','inscribir','fecha','fechas']::text[], '[{"label":"SIU Guaraní","url":"https://autogestion.guarani.unlp.edu.ar/acceso"},{"label":"Calendario académico","match":"Calendario ano lectivo completo"}]'::jsonb, 4, 6),
  ('prorroga', 'finales', 'Se me vence la cursada, ¿puedo pedir prórroga?', array['Sí, la Facultad tiene un formulario para pedir prórroga para rendir el final. Pedila antes de que se venza.']::text[], array['vence','vencimiento','vencio','prorroga','extender','extension','cursada','regularidad','final']::text[], '[{"label":"Pedir prórroga","match":"Prorroga para rendir final"}]'::jsonb, null, 7),
  ('parciales-viejos', 'finales', '¿Dónde consigo parciales y finales viejos?', array['En la Nube de Gradiente: más de 2.600 archivos ordenados por materia. En Mi plan te marcamos con una carpetita las materias que tienen material.']::text[], array['parcial','parciales','final','finales','viejos','resueltos','modelo','nube','drive','examenes']::text[], '[{"label":"Abrir la nube","match":"Nube de apuntes y parciales"}]'::jsonb, 5, 8),
  ('siu-cuenta', 'tramites', '¿Cómo creo mi cuenta de SIU Guaraní?', array['Desde la página de acceso de SIU Guaraní de la UNLP. Si ya tenés cuenta y no podés entrar, probá recuperar la contraseña desde ahí mismo.']::text[], array['siu','guarani','cuenta','usuario','contrasena','clave','entrar','acceso','olvide']::text[], '[{"label":"Ir a SIU Guaraní","url":"https://autogestion.guarani.unlp.edu.ar/acceso"}]'::jsonb, null, 9),
  ('certificado', 'tramites', '¿Cómo saco un certificado o constancia?', array['Los trámites, certificados y servicios para estudiantes están explicados en la página de Estudiantes de la Facultad. Si hace falta ir en persona, sacá turno antes.']::text[], array['certificado','constancia','alumno','regular','analitico','tramite','tramites','papel']::text[], '[{"label":"Trámites de estudiantes","match":"Estudiantes FI (tramites, certificados y servicios)"},{"label":"Sacar turno","match":"Turnos FI para tramites"}]'::jsonb, null, 10),
  ('turno', 'tramites', '¿Cómo saco turno para un trámite?', array['La Facultad da turnos online para la atención presencial.']::text[], array['turno','turnos','alumnos','departamento','atencion','presencial','ventanilla']::text[], '[{"label":"Sacar turno","match":"Turnos FI para tramites"}]'::jsonb, null, 11),
  ('correo', 'tramites', '¿Cómo pido el correo institucional?', array['Se pide desde la web de soporte de la Facultad.']::text[], array['correo','mail','email','institucional','cuenta','ing']::text[], '[{"label":"Pedir correo","match":"Solicitud de correo institucional para alumnos"}]'::jsonb, null, 12),
  ('mail-profe', 'profes', '¿Cómo consigo el mail de un profe o de la cátedra?', array['Buscá la materia y te mostramos el mail de contacto de la cátedra, su página y el Portal de Asignaturas. Casi todas tienen un mail general que lee el equipo docente.','Para dudas del día a día, el aula virtual de la materia suele ser lo más rápido.']::text[], array['mail','correo','email','profe','profesor','profesora','docente','catedra','contacto','escribir','ayudante','jtp','titular']::text[], '[{"label":"Buscar el mail de la cátedra","go":"catedra"},{"label":"Portal de asignaturas","match":"Portal de Asignaturas FI"}]'::jsonb, null, 13),
  ('escribir-profe', 'profes', '¿Cómo le escribo a un profe para hacer una consulta?', array['Mandalo desde tu mail institucional si lo tenés. En el asunto poné materia, comisión y tema (por ejemplo: «Matemática B – Com. 3 – Consulta TP 2»).','Arrancá con nombre, apellido y número de alumno, y andá al grano. Si es una duda de contenido, muchas veces conviene ir directo a la clase de consulta.']::text[], array['escribir','mail','consulta','profe','profesor','docente','asunto','redactar','mensaje','como','pregunto']::text[], '[{"label":"Buscar el mail de la cátedra","go":"catedra"},{"label":"Pedir correo institucional","match":"Solicitud de correo institucional para alumnos"}]'::jsonb, null, 14),
  ('horario-consulta', 'profes', '¿Cuándo son las clases de consulta?', array['Cada cátedra tiene sus propios horarios de consulta. Suelen estar en la página de la cátedra o en su aula virtual.','Si no los encontrás, escribile al mail de contacto de la cátedra y preguntá.']::text[], array['consulta','consultas','horario','horarios','clase','dudas','practica','ayudante']::text[], '[{"label":"Buscar la cátedra","go":"catedra"},{"label":"Aulas y horarios","match":"Aulas y horarios"}]'::jsonb, null, 15),
  ('revision', 'profes', 'No estoy de acuerdo con mi nota, ¿qué hago?', array['Pedí ver el examen: la revisión es tu derecho. La cátedra suele avisar en el aula virtual cuándo es la muestra de parciales; si no, preguntá por mail.','Si después de la revisión sentís que algo no estuvo bien, escribinos y te acompañamos.']::text[], array['nota','revision','revisar','examen','parcial','reclamo','corregir','correccion','muestra','desaprobe','injusto']::text[], '[{"label":"Buscar el mail de la cátedra","go":"catedra"},{"label":"Escribirnos","go":"consulta"}]'::jsonb, null, 16),
  ('problema-catedra', 'profes', 'Tengo un problema con un profe o una cátedra', array['Primero intentá hablarlo con la cátedra (tu ayudante, el JTP o el titular). Si no se resuelve, podés ir al Departamento de tu carrera o a la Dirección de Enseñanza.','Si no querés hacerlo solo, escribinos: como agrupación te acompañamos y lo tratamos con discreción.']::text[], array['problema','profe','profesor','catedra','trato','maltrato','reclamo','queja','denuncia','conflicto','injusto']::text[], '[{"label":"Escribirnos","go":"consulta"},{"label":"Mail a Enseñanza","url":"mailto:ensenanza@ing.unlp.edu.ar"}]'::jsonb, null, 17),
  ('paro', 'cursada', '¿Hay clases? ¿Hay paro o feriado?', array['En el calendario del inicio están los feriados, asuetos y fechas de la Facultad. Cuando hay paro o un aviso importante, también lo marcamos ahí.']::text[], array['paro','clases','feriado','asueto','hay','manana','hoy','calendario','fecha','fechas','suspension','no laborable']::text[], '[{"label":"Ver el calendario","go":"cal"},{"label":"Calendario oficial","match":"Calendario ano lectivo completo"}]'::jsonb, null, 18),
  ('contacto-facu', 'tramites', '¿A quién le escribo por un problema con la cursada?', array['Para temas académicos (inscripciones, correlativas, mesas) escribile a la Dirección de Enseñanza. Para becas y bienestar, a Asuntos Estudiantiles.','Si no sabés por dónde arrancar, mandanos la consulta y te orientamos.']::text[], array['problema','reclamo','escribir','mail','contacto','ensenanza','asuntos','estudiantiles','ayuda']::text[], '[{"label":"Mail a Enseñanza","url":"mailto:ensenanza@ing.unlp.edu.ar"},{"label":"Mail a Asuntos Estudiantiles","url":"mailto:asuntos.estudiantiles@ing.unlp.edu.ar"}]'::jsonb, null, 19),
  ('becas', 'becas', '¿Qué becas hay?', array['Hay becas de la Facultad y de la UNLP (ayuda económica, comedor, transporte, entre otras). Las convocatorias abren en fechas puntuales, así que conviene revisar seguido.']::text[], array['beca','becas','plata','ayuda','economica','comedor','transporte','bienestar']::text[], '[{"label":"Becas y pasantías","match":"Becas y pasantias FI"}]'::jsonb, null, 20),
  ('trabajo', 'becas', 'Trabajo, ¿hay algo para estudiantes que trabajan?', array['Sí, la Facultad tiene un programa para estudiantes trabajadores (RET) con algunas facilidades para la cursada.']::text[], array['trabajo','trabajador','trabajadora','laburo','laburo','ret','horario','facilidades']::text[], '[{"label":"Programa RET","match":"Programa para estudiantes trabajadores (RET)"}]'::jsonb, null, 21),
  ('ingresante', 'ingreso', 'Soy ingresante, ¿por dónde arranco?', array['Empezá por la guía oficial para ingresantes y la página de la cátedra de ingreso. Creá tu cuenta de SIU Guaraní, que la vas a usar para todo.','Y cuando termines el ingreso, armá tu plan acá para ver qué cursar.']::text[], array['ingresante','ingreso','nuevo','nueva','empiezo','primer','primero','arranco','curso','nivelacion']::text[], '[{"label":"Guía para ingresantes","match":"Guia oficial para ingresantes FI-UNLP"},{"label":"Cátedra de ingreso","match":"Catedra de ingreso"}]'::jsonb, null, 22),
  ('que-es', 'gradiente', '¿Qué es Gradiente?', array['Somos una agrupación estudiantil de Ingeniería UNLP. Hacemos la Nube de apuntes, la mesita de librería en Electro, esta web y te ayudamos con lo que necesites.']::text[], array['gradiente','agrupacion','quienes','somos','centro','estudiantes']::text[], '[{"label":"Conocenos","go":"about"}]'::jsonb, null, 23),
  ('mesita', 'gradiente', '¿Dónde está la mesita y qué vende?', array['Estamos con la mesita en el edificio de Electro. Tenemos kits de cuadernos y útiles a precio estudiante.']::text[], array['mesita','kiosco','libreria','cuaderno','utiles','comprar','precio','electro','kit']::text[], '[{"label":"Ver la mesita","go":"#/mesita"}]'::jsonb, null, 24),
  ('sumarme', 'gradiente', '¿Cómo me sumo a Gradiente?', array['¡Escribinos! Por Instagram, WhatsApp o pasando por la mesita en Electro.']::text[], array['sumo','sumarme','participar','militar','unirme','ayudar','voluntario']::text[], '[{"label":"Instagram","url":"https://instagram.com/gradienteingenieriaunlp"},{"label":"WhatsApp","url":"https://chat.whatsapp.com/CRnDHAhup938Nk4uJ8TBVp"}]'::jsonb, null, 25);

-- cátedras: la tabla guarda solo las correcciones del equipo; la app las aplica encima de data/catedras.json
